// ============================================
// Project Dashboard - Mock Data
// ============================================

import type { Project, ProjectManager } from './types';

const defaultPM: ProjectManager = {
    name: 'Budi Santoso',
    role: 'Project Manager',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    phone: '6281234567890',
};

export const allProjects: Project[] = [
    {
        id: 1,
        title: 'Renovasi Villa Bali',
        location: 'Ubud, Bali',
        status: 'on-track',
        workPhase: 'CONSTRUCTION',
        progress: 45,
        lastUpdate: '2 jam lalu',
        image: 'https://images.unsplash.com/photo-1600596542815-6ad4c727dd2d?auto=format&fit=crop&w=800&q=80',
        statusLabel: 'On Track',
        description: 'Proyek renovasi villa modern dengan konsep tropical minimalist di kawasan Ubud. Meliputi renovasi struktur, interior, dan landscape.',
        startDate: '1 Des 2024',
        targetDate: '1 Mar 2025',
        pm: defaultPM,
    },
    {
        id: 2,
        title: 'Pembangunan Ruko Kemang',
        location: 'Kemang, Jakarta Selatan',
        status: 'attention',
        workPhase: 'RAB',
        progress: 30,
        lastUpdate: '1 hari lalu',
        image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
        statusLabel: 'Perlu Review',
        description: 'Pembangunan ruko 3 lantai dengan desain modern di area komersial Kemang. Terdapat kendala material yang perlu ditinjau.',
        startDate: '15 Nov 2024',
        targetDate: '15 Apr 2025',
        pm: { ...defaultPM, name: 'Ahmad Wijaya' },
    },
    {
        id: 3,
        title: 'Interior Cafe Senopati',
        location: 'Senopati, Jakarta',
        status: 'on-track',
        workPhase: 'FINISHING',
        progress: 65,
        lastUpdate: 'Baru saja',
        image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
        statusLabel: 'On Track',
        description: 'Desain interior cafe dengan tema industrial modern untuk brand coffee shop premium.',
        startDate: '1 Nov 2024',
        targetDate: '1 Feb 2025',
        pm: defaultPM,
    },
    {
        id: 4,
        title: 'Rumah Minimalis Bandung',
        location: 'Dago, Bandung',
        status: 'on-track',
        workPhase: 'FINISHING',
        progress: 75,
        lastUpdate: '5 jam lalu',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
        statusLabel: 'On Track',
        description: 'Pembangunan rumah 2 lantai dengan konsep minimalis modern di kawasan Dago.',
        startDate: '1 Okt 2024',
        targetDate: '1 Feb 2025',
        pm: { ...defaultPM, name: 'Siti Rahma' },
    },
    {
        id: 5,
        title: 'Apartemen Surabaya Tower A',
        location: 'Surabaya Barat',
        status: 'completed',
        workPhase: 'HANDOVER',
        progress: 100,
        lastUpdate: '1 minggu lalu',
        image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
        statusLabel: 'Selesai',
        description: 'Unit apartemen dengan finishing premium telah selesai dikerjakan.',
        startDate: '1 Jun 2024',
        targetDate: '1 Des 2024',
        pm: defaultPM,
    },
    {
        id: 6,
        title: 'Restaurant Bali Cliff',
        location: 'Uluwatu, Bali',
        status: 'completed',
        workPhase: 'HANDOVER',
        progress: 100,
        lastUpdate: '2 minggu lalu',
        image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80',
        statusLabel: 'Selesai',
        description: 'Restoran tepi tebing dengan pemandangan sunset yang memukau.',
        startDate: '1 Mei 2024',
        targetDate: '1 Nov 2024',
        pm: { ...defaultPM, name: 'Dewi Kartika' },
    },
    {
        id: 7,
        title: 'Office Tower Sudirman',
        location: 'SCBD, Jakarta',
        status: 'on-track',
        workPhase: 'CONSTRUCTION',
        progress: 60,
        lastUpdate: '3 jam lalu',
        image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
        statusLabel: 'On Track',
        description: 'Fit-out kantor dengan desain open space modern untuk perusahaan teknologi.',
        startDate: '1 Des 2024',
        targetDate: '1 Apr 2025',
        pm: defaultPM,
    },
    {
        id: 8,
        title: 'Villa Tepi Pantai Lombok',
        location: 'Senggigi, Lombok',
        status: 'attention',
        workPhase: 'DESIGN',
        progress: 25,
        lastUpdate: '2 hari lalu',
        image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80',
        statusLabel: 'Delayed',
        description: 'Villa resort dengan akses langsung ke pantai. Mengalami keterlambatan pengiriman material.',
        startDate: '1 Okt 2024',
        targetDate: '1 Mar 2025',
        pm: { ...defaultPM, name: 'Rudi Hermawan' },
    },
    {
        id: 9,
        title: 'Warehouse Cikarang',
        location: 'Cikarang, Bekasi',
        status: 'completed',
        workPhase: 'HANDOVER',
        progress: 100,
        lastUpdate: '1 bulan lalu',
        image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
        statusLabel: 'Selesai',
        description: 'Gudang logistik dengan standar internasional untuk e-commerce.',
        startDate: '1 Apr 2024',
        targetDate: '1 Okt 2024',
        pm: defaultPM,
    },
    {
        id: 10,
        title: 'Showroom Mobil Premium',
        location: 'PIK, Jakarta Utara',
        status: 'on-track',
        workPhase: 'CONSTRUCTION',
        progress: 55,
        lastUpdate: '6 jam lalu',
        image: 'https://images.unsplash.com/photo-1567449303078-57ad995bd329?auto=format&fit=crop&w=800&q=80',
        statusLabel: 'On Track',
        description: 'Showroom mobil mewah dengan desain futuristik dan area test drive.',
        startDate: '15 Nov 2024',
        targetDate: '15 Mar 2025',
        pm: { ...defaultPM, name: 'Joko Prasetyo' },
    },
    {
        id: 11,
        title: 'Hotel Boutique Yogyakarta',
        location: 'Malioboro, Yogyakarta',
        status: 'completed',
        workPhase: 'HANDOVER',
        progress: 100,
        lastUpdate: '3 minggu lalu',
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
        statusLabel: 'Selesai',
        description: 'Hotel boutique dengan sentuhan budaya Jawa yang otentik.',
        startDate: '1 Mar 2024',
        targetDate: '1 Okt 2024',
        pm: defaultPM,
    },
    {
        id: 12,
        title: 'Renovasi Rumah Heritage',
        location: 'Menteng, Jakarta Pusat',
        status: 'completed',
        workPhase: 'HANDOVER',
        progress: 100,
        lastUpdate: 'Hari ini',
        image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
        statusLabel: 'Selesai',
        description: 'Renovasi rumah heritage dengan preservasi arsitektur kolonial klasik.',
        startDate: '1 Jul 2024',
        targetDate: '1 Des 2024',
        pm: { ...defaultPM, name: 'Maya Putri' },
    },
];
